data: {{data_dir}}/data
save_model: {{exp_dir}}/model
log_file: {{exp_dir}}/log.txt
# train_from: exp/calculus__differentiate/model_step_1000.pt
save_checkpoint_steps: 1000
keep_checkpoint: 3
seed: 20200127
train_steps: 1000
valid_steps: 100
# warmup_steps: 8000
report_every: 10

decoder_type: transformer
encoder_type: transformer
word_vec_size: 64
rnn_size: 64
layers: 2
transformer_ff: 256
heads: 1

# accum_count: 2
optim: adam
adam_beta1: 0.9
adam_beta2: 0.995
# decay_method: noam
learning_rate: 0.0006
max_grad_norm: 0.1

batch_size: 1024
# batch_type: tokens
# normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

# world_size: 4
# gpu_ranks:
# - 0
# - 1
# - 2
# - 3
